components/grid/overview.md

The ref value wasn't pointing to an actual property.

Fix ref value

---

_contentTemplates/common/get-started.md

The Blazor VS extension is no longer need with Preview 7+

Removed Blazor extension info

---

components/treeview/drag-drop.md

Points of possible further discussion:
I have made the examples in separate sections because:
- They were too long to be on a single page
- Maybe it is not a bad idea to showcase how an app should be structured to the users as we have more and more tickets regarding the general behavior of  the framework
Shall we leave them like that?

Add docs for the drag and drop feature of the TreeView

---

knowledge-base/editor-content-selection.md
knowledge-base/editor-get-selection.md

KB article on how to get the selected content from the editor

---

components/grid/filter/checkboxlist.md

fixed typo
* OnClick
* OnChange
* ValueChanged
* OnRead
* etc.

Update checkboxlist.md (fixed a typo)

---

components/grid/editing/overview.md

Changed contructor to constructor.

Spelling error in Grid docs

---

_contentTemplates/editor/general.md
components/editor/overview.md
components/editor/paste-cleanup.md

docs(editor): paste cleanup initial

---

knowledge-base/date-input-select-am-pm-on-keypress.md

kb(date-input):Select AM/PM by pressing A or P on keyboard

---

_config.yml
components/mediaquery/events.md
components/mediaquery/integration.md
components/mediaquery/overview.md

* OnClick
* OnChange
* ValueChanged
* OnRead
* etc.

Docs media query

---

troubleshooting/js-errors.md

People keep missing this instruction, let's hope a code snippet clarifies it.

chore(troubleshooting): add snippet for defer attribute

---

components/grid/templates/editor.md

Included a link to the notes section of the editing/overview article as per the note in 1525025

chore(grid):link editing/overview notes section

---

components/form/formitems/overview.md
components/form/overview.md

Improvement based on the following customer feedback from 21 Jun 2021 8:07 PM:
"This statement is confusing: Enabled - bool - whether the editor is disabled. Defaults to true and the Form takes its value from the [Enabled] data annotation attribute. Do you mean the [Editable] data annotation attribute?"

chore(form):clarification for the Enabled parameter of the FormIem

---

components/grid/templates/column-header.md
knowledge-base/grid-center-column-header-content.md
knowledge-base/grid-wrap-and-center-column-text.md

- Fixed snippet in Header Template article - the style was outdated.
- Linked kb-s for column header content center and wrap and center: to each other and from the Header Template article

Grid Header Template fix and kb linking

---

knowledge-base/inputs-set-focus.md

Ticket ID: 1527317 and other similar questions.

kb(inputs): how to use FocusAsync

---

knowledge-base/notification-custom-position.md

- Add an example with fixed positioning and centered position
- Remove the TileLayout
- Improve SEO for centered scenarios

docs: Improve Notification custom position KB

---

components/grid/virtual-scrolling.md

That's what happens when you don't use nameof() ;)

chore(grid): fix typo in field name

---

knowledge-base/scheduler-load-on-demand.md

KB for https://github.com/telerik/blazor-ui/tree/master/scheduler/load-appointments-on-demand

kb(scheduler): load on demand

---

knowledge-base/grid-scroll-to-selected-row.md

For https://github.com/telerik/blazor-ui/pull/116

kb(grid): scroll to selected row

---

components/drawer/navigation.md
knowledge-base/drawer-sync-selected-item.md

For https://github.com/telerik/blazor-ui/pull/112

chore(drawer): link sample for syncing selected item

---

_contentTemplates/treelist/databinding.md
components/grid/columns/bound.md
components/grid/data-binding.md
components/grid/overview.md
components/treelist/data-binding/interface.md
components/treelist/data-binding/overview.md

* Moved the Grid data binding info from Overview to a separate article.
* The Grid and TreeList interface-related stuff is currently documented differently, in the way, which made most sense to me (Interface section in the single data binding article for the Grid, separate Interface article for the TreeList).

Add Grid and TreeList interface binding docs

---

components/treelist/state.md

This PR fixes an unhandled exception caused by an interop call in the prerendering phase.

TreeList State LocalStorage example fix

---

components/breadcrumb/overview.md

Fixes the API reference within the Overview page

chore(breadcrumb): fix api ref in overview

---

_config.yml

This change will allow us to change the CTA panel text from blazor-docs, instead of docs-seed.

docs: Allow override of CTA message from blazor-docs

---

.gitignore

Currently .gitignore has Windows line endings -
* The other files use Unix LE
* When I copy the docs-seed assets to the blazor-docs folder (`sh copy_local.sh ...`), this always marks the .gitignore file as changed.

docs: Switch .gitignore to Unix line endings

---

components/grid/grouping/load-on-demand.md

Based on feedback from https://feedback.telerik.com/blazor/1545573-row-virtualization-and-load-groups-on-demand-ignore-pagesize-value

docs: Improve Grid Load Groups on Demand

---

integrations/fiddler-jam.md

It turned out that our documentation pages are ranked better than the Fiddler documentation. Thus, we are reducing our content and Fiddler information in the article.

Update fiddler jam article to generate less traffic

---

knowledge-base/carousel-more-than-one-item-in-viewport.md

In old suites like WebForms the rotator has a setting for item size and viewport size, so it is a tad easier to show several items at once with a flat data source. That has other implications which make responsive design very hard, however, and is an approach not used in more modern suites.

kb(carousel): more than one item in viewport

---

knowledge-base/grid-collapse-groups-by-default.md

Added a knowledge base article to programmatically collapse Grid Groups on initialize when paging.

kb(grid): added kb for grid collapse groups by default

---

components/button/disabled-button.md
components/button/overview.md
components/button/styling.md

This PR updates the Button component Overview page according to the guidelines [in this document](https://progresssoftware-my.sharepoint.com/:w:/g/personal/ymitev_progress_com/EXwTNq51uIxIrstak1fv1BABO6BN08SR3A4zhoubKvknyg?e=Sjz3uT).
The Button is one of the ten initial components that will undergo this transformation.

Update Button Overview

---

_config.yml
components/fileselect/events.md
components/fileselect/overview.md
components/fileselect/validation.md
components/upload/validation.md

Fileselect docs

---

components/calendar/overview.md

This PR updates the Calendar component Overview page according to the guidelines [in this document](https://progresssoftware-my.sharepoint.com/:w:/g/personal/ymitev_progress_com/EXwTNq51uIxIrstak1fv1BABO6BN08SR3A4zhoubKvknyg?e=Sjz3uT).
The Calendar is one of the ten initial components that will undergo this transformation.

Update Calendar Overview

---

components/upload/overview.md

docs: Update Upload file size limits guidance

---

components/datepicker/overview.md

-Removed the default hardcoded width on the features section of the overview.

docs(datepciker): removed default hardcoded width

---

components/tilelayout/events.md

ShouldRender is not present in the tilelayout event args

chore(tilelayout): remove ShouldRender from events article

---

_config.yml
_contentTemplates/common/get-started.md
common-features/data-binding/observable-data.md
common-features/data-binding/onread.md
common-features/data-binding/overview.md
components/autocomplete/events.md
components/combobox/events.md
components/dropdownlist/events.md
components/grid/manual-operations.md
components/listview/events.md
components/listview/manual-operations.md
components/multiselect/events.md

This PR includes 2 new common data binding articles - one for Overview + `Data` and one for `OnRead`.
I also included some links to these new articles on other Getting Started pages and data-binding-related articles.
In a next iteration, I will polish the data binding articles of all components to integrate better with these new pages.

docs(common): Add common Data Binding section

---

components/combobox/refresh-data.md

The cause of this error is most likely copy-pasting from https://docs.telerik.com/blazor-ui/components/autocomplete/refresh-data#rebind-method.

Blazor-Docs: Fix typo in components/combobox/refresh-data.md

---

components/filemanager/data-binding/hierarchical-data.md

The root directory needs the 'HasDirectories' property set to true for the component to display the child directories.

Missing property in hardcoded data generation

---

knowledge-base/grid-cascade-dropdowns-for-fields.md

Idea from 
https://www.telerik.com/forums/cascading-dropdownlist-in-grid-editing-inline---article-needs-to-be-adjusted

kb(grid): improve cascading dropdowns KB to handle initial data load

---

components/calendar/navigation.md

- Added the TopView property near the BottomView description
- Example improved by setting the TopView there as well

docs(calendar):Add TopView property

---

upgrade/framework-versions.md

Added a generic explanation for future preview .NET versions. The text is based on a .NET 6 text that we deleted some time ago.

docs(common): Clarify preview .NET versions support

---

common-features/font-icons.md

- The JS that gets the icons list from JSON was broken due to a recent change in that JSON.

Fixed Font Icons page

---

components/animationcontainer/overview.md

docs(animationcontainer): Remove deprecated demos links

---

components/grid/export/events.md

Added note that `Width` and `NumberFormat` properties are not applicable for CSV export

docs(grid):Updated OnBeforeCSVExport docs

---

components/panelbar/overview.md

Note: removed Reference section as there are no exposed methods for the component, so the section does not have value.

docs(panelbar):Revamp Overview

---

components/editor/built-in-tools.md
components/editor/custom-tools.md
components/editor/overview.md
components/editor/toolbar.md
knowledge-base/editor-get-selection.md

* Switched the table layout to auto.
* Optimized the table columns.
* Added some examples to make the "raw" documentation easier to understand.

docs(editor): Revamp tools and commands

---

accessibility/accessibility-swatch.md
knowledge-base/common-theme-customization-options.md
knowledge-base/common-themebuilder-json-from-scss.md
styling-and-themes/custom-theme.md
styling-and-themes/swatch-distribution.md
styling-and-themes/theme-swatches.md
upgrade/breaking-changes/3-0-0.md

This PR updates the ThemeBuilder section in the Custom Themes article and replaces the link to the SASS ThemeBuilder with the link to the new ThemeBuilder Pro in a few related documents.

Update the ThemeBuilder Docs for the Initial Release

---

_config.yml
common-features/input-validation.md
components/signature/appearance.md
components/signature/events.md
components/signature/overview.md

Related to https://github.com/telerik/blazor/issues/5042

[3.7.0] Documentation for the Signature component 

---

components/dateinput/overview.md
components/datepicker/overview.md
components/datetimepicker/overview.md
components/timepicker/overview.md

[3.7] docs(datetime pickers): Document AutoComplete parameter

---

components/scheduler/events.md

[3.7] docs(scheduler): Update OnCellRender docs

---

_contentTemplates/dropdowns/methods.md
components/autocomplete/overview.md
components/combobox/overview.md
components/dropdownlist/overview.md
components/multicolumncombobox/overview.md
components/multiselect/overview.md

Related to: https://github.com/telerik/blazor/issues/6247.

[4.1] docs(selects): add refresh method for selects

---

components/grid/events.md

The background was not applied to `k-alt` rows due to selector specificity.

chore(grid):fix CSS selectors in OnRowRender example

---

.github/workflows/sync-a11y.yml

Dependabot defaults to [read-only permissions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions) and fails to push changes.

chore: grant write permissions to sync build

---

knowledge-base/fileselect-upload-hide-file-list.md

Drop hint of the FileSelect was visible

chore(upload,fileselect): fix kb example to ensure the drop hint is hidden

---

components/grid/export/events.md

_Based on customer feedback_:
We are customizing the export to take only the selected items. However, there are no initially selected items. If one tries to export without selecting anything, at first this gives the impression that the export does not work as the exported file is empty.

Update samples in customize export article

---

components/dialog/predefined.md

Related to: [telerik/blazor#6820](https://github.com/telerik/blazor/issues/6820)

docs(dialog): Include an example of configuring the default input text in a prompt dialog

---

components/autocomplete/overview.md
components/combobox/overview.md
components/dateinput/overview.md
components/datepicker/overview.md
components/daterangepicker/overview.md
components/datetimepicker/overview.md
components/dropdownlist/overview.md
components/editor/overview.md
components/maskedtextbox/overview.md
components/multicolumncombobox/overview.md
components/multiselect/overview.md
components/numerictextbox/overview.md
components/textarea/overview.md
components/textbox/overview.md
components/timepicker/overview.md

Related to: telerik/blazor#6965

docs(inputs): add readonly parameter in the parameters section

---

components/pivotgrid/overview.md

Related to: https://github.com/telerik/blazor/issues/6907.

[4.4] docs(pivotgrid): add title parameter

---

components/contextmenu/icons.md
components/contextmenu/navigation.md
components/contextmenu/refresh-data.md
components/gridlayout/items.md
components/menu/icons.md
components/menu/navigation.md
components/panelbar/icons.md
components/tabstrip/header-template.md
components/toolbar/events.md
components/treeview/icons.md
knowledge-base/common-custom-font-icons-fail.md
knowledge-base/icon-new-names.md

Related to https://github.com/telerik/kendo-icons/pull/162

[4.4] chore: fix typo in envelope icons

---

styling-and-themes/themebuilder.md

Removing a note containing outdated information - multiple new tiers are already available and themes created with previous TB versions are unusable.

Remove Note in themebuilder.md

---

components/gantt/timeline/templates/tooltip.md

There was an incorrect end tag for the TelerikFontIcon

docs(gantt): fix tooltip example

---

components/filemanager/overview.md

The code used to throw a null reference error when adding a new item on root level.

docs(filemanager): update overview sample

---

styling-and-themes/custom-theme.md
styling-and-themes/themebuilder.md

Related to the `$primary` being renamed to `$kendo-color-primary`

docs(themes): Update primary color mentions

---

common-features/input-validation.md

Slider-related margin fix is due to https://github.com/telerik/kendo-themes/issues/4698

docs(input validation): fix examples for MaskedTextbox and Slider

---

components/treeview/checkboxes/overview.md

There was an incorrect end tag for the TelerikFontIcon

docs(treeview): fix checkbox example

---

common-features/icons.md
knowledge-base/font-icons-not-rendering.md

Related to: https://github.com/telerik/blazor/issues/7485

Documentation on missing font icons in 4.6.0

---

upgrade/rendering-changes/4-6-0.md

Related to: https://github.com/telerik/blazor/issues/6345

4.6.0 Rendering Changes article

---

knowledge-base/chart-draw-horizontal-vertical-lines.md

Related to: https://github.com/telerik/blazor/issues/7584

docs(charts): add kb for drawing horizontal and vertical lines

---

knowledge-base/grid-conditional-cell-background.md

One of the custom CSS selectors did not work because it had lower specificity than one of our CSS selectors.

docs(grid): fix grid knowledge base example

---

components/grid/editing/overview.md
components/scheduler/editing/edit-appointments.md

Related to: [#7373](https://github.com/telerik/blazor/issues/7373)

docs(grid, scheduler): add read-only properties documentation

---

knowledge-base/tooltip-in-grid.md

endless loop in OnAfterRenderAsync caused by StateHasChanged()

docs(tooltip): Fix broken example

---

components/autocomplete/overview.md
components/combobox/overview.md
components/multicolumncombobox/overview.md
components/multiselect/overview.md

https://github.com/telerik/blazor/issues/8369#issuecomment-1908797748

docs(selects): document LoaderShowDelay parameter

---

components/dialog/predefined.md

Related to: https://github.com/telerik/blazor/issues/8523.

[5.1] docs(dialog): add samples for customizing predefined dialog buttons

---

components/chart/trendlines.md

Related to: https://github.com/telerik/blazor/issues/7966.

[5.1] docs(charts): update trendline articles to include the new types

---

knowledge-base/common-css-isolation.md

Manually cherry-picking the changes from https://github.com/telerik/blazor-docs/pull/1980, as the automatic cherry-pick [failed](https://github.com/telerik/blazor-docs/pull/1980#issuecomment-2009596026).

kb(cssIsolation): make snippets non-runnable (#1980)

---

components/aiprompt/overview.md

Removing the auto-layout as the table doesn't render correctly on small screens.

docs(AIPrompt): Remove events from parameters table

---

_contentTemplates/common/observable-data.md
common-features/data-binding/overview.md
common-features/input-validation.md
components/autocomplete/data-bind.md
components/autocomplete/overview.md
components/combobox/data-bind.md
components/combobox/events.md
components/dropdownlist/data-bind.md
components/dropdownlist/events.md
components/gantt/gantt-tree/columns/bound.md
components/grid/columns/bound.md
components/listbox/overview.md
components/multicolumncombobox/data-bind.md
components/multiselect/data-bind.md
components/radiogroup/data-bind.md
components/radiogroup/events.md
components/radiogroup/overview.md
components/treelist/columns/bound.md
getting-started/value-vs-data-binding.md
knowledge-base/combobox-not-closing.md
knowledge-base/dropdown-all-items-are-selected.md
knowledge-base/dropdowns-get-model.md
knowledge-base/grid-aggregates-and-datatable.md
knowledge-base/grid-bind-navigation-property-complex-object.md
knowledge-base/grid-filter-column-list.md
knowledge-base/grid-save-load-state-localstorage.md

Triggered by docs feedback. Refer to:
https://learn.microsoft.com/en-us/dotnet/api/system.type.isprimitive?view=net-8.0#remarks
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types
So, our mentioning of "primitive" types is more restrictive than it should be.

docs(common): Fix incorrect mentioning of primitive types

---

knowledge-base/common-failed-to-find.md
troubleshooting/general-issues.md

Related to: https://github.com/telerik/blazor/issues/8936

docs(common)troubleshooting - add Failed to find error

---

components/chip/overview.md

Related to : [#8861](https://github.com/telerik/blazor/issues/8861)

docs(Chip): add aria-label and id parameters

---

components/treelist/virtual-scrolling.md

Related to: https://github.com/telerik/blazor/issues/8690

TreeList Virtual Scrolling 

---

knowledge-base/chart-export-to-image.md

Related to: https://github.com/telerik/blazor/issues/7634

docs(chart):add KB to link to export example

---

components/gantt/timeline/templates/task.md
knowledge-base/gantt-different-colors-for-tasks.md

Related to https://github.com/telerik/blazor/issues/4263

kb(gantt): different colors for tasks

---

components/popover/overview.md

- The correct enum is https://docs.telerik.com/blazor-ui/api/telerik.blazor.components.popovershowon
- it is a nullable parameter with no default value, as this way it caters for the case where programmatic approach only is desired.
The default value here is misleading - this was never the case in the component and is an issue only in the documentation

fix(popover): use correct enum name and type for showon param

---

knowledge-base/chart-draw-horizontal-vertical-lines.md
knowledge-base/grid-filter-column-list.md

Related to: https://github.com/telerik/blazor/issues/9612

docs(Grid): update examples in kb articles

---

_config.yml
_contentTemplates/editor/general.md
components/editor/overview.md
components/editor/prosemirror-plugins.md
components/editor/prosemirror-schema/create-new-schema.md
components/editor/prosemirror-schema/modify-default-schema.md
components/editor/prosemirror-schema/overview.md

Related to https://github.com/telerik/blazor/issues/9377 and https://github.com/telerik/blazor/issues/9371

Editor enhancements docs

---

_contentTemplates/common/inputs.md

docs(floating): fix the CSS selector for prefix and floating label

---

components/fileselect/templates.md
knowledge-base/common-telerik-themes-libman.md
knowledge-base/common-value-cannot-be-null-parameter-format.md
knowledge-base/grid-persist-selection-across-pages.md
styling-and-themes/override-theme-styles.md

Closes https://github.com/telerik/blazor/issues/9810.

chore(common): fix broken links

---

common-features/icons.md

docs(icons): Improve custom icons documentation

---

knowledge-base/checkbox-custom-icon.md

Related to: https://github.com/telerik/blazor/issues/9852

Ravamp KB article for Checkbox icon change

---

_contentTemplates/dropdowns/features.md
components/autocomplete/overview.md
components/combobox/overview.md
components/dropdownbutton/overview.md
components/dropdownlist/overview.md
components/multiselect/overview.md

Related to: https://github.com/telerik/blazor/issues/9679

Update popup settings section

---

_contentTemplates/common/observable-data.md
components/form/events.md
components/form/formitems/buttons.md
components/grid/virtual-scrolling.md
components/spreadsheet/overview.md

Related to: https://github.com/telerik/blazor/issues/9871

chore: apply seo recommendation

---

knowledge-base/dropdowns-get-model.md

Remove the tip that links to an already implemented feature request.

docs(Dropdowns): remove outdated information

---

components/grid/refresh-data.md
components/grid/virtual-scrolling.md

Related to https://github.com/telerik/blazor/issues/10132

chore: apply marketing recommendations

---

_config.yml

We append a suffix to each page's metadata description. The guidelines from our marketing team is that these add little to no value and simply bloat the content, hence we should remove them.

chore: remove head metadata description suffix

---

components/scheduler/templates/appointment.md
components/scheduler/templates/dateheader.md
components/scheduler/templates/resource-grouping-header.md
components/scheduler/templates/slot.md

Related to:
https://github.com/telerik/blazor/issues/10094#issuecomment-2360771870 - In general, while we still support NET6 we won't be able to expose the SchedulerResourceGroupHeaderTemplate on the root level of the Scheduler
and
https://github.com/telerik/blazor/pull/10098#issuecomment-2360393620 - The demos won't be separated for each template, so we need to update the references

docs(Scheduler):revamp resource grouping header template docs

---

components/mediaquery/integration.md
components/mediaquery/overview.md

Related to https://github.com/telerik/blazor-ui/pull/307

docs(mediaquery): Replace obsolete Form Integration demo

---

knowledge-base/dropdownlist-kb-nodatatext.md
knowledge-base/grid-column-in-custom-component-is-last.md
knowledge-base/grid-filterrow-bool-customization.md
knowledge-base/grid-hide-pager-when-no-data.md
knowledge-base/grid-pre-select-checkbox-filter.md
knowledge-base/grid-search-startswith.md
knowledge-base/grid-set-all-page-size-option-as-default.md
knowledge-base/window-modal-minimize-popup.md

Related to: https://github.com/telerik/blazor/issues/10223

chore: apply seo recommendations

---

components/treelist/filter/searchbox.md

Currently, we do not expose the OnRead event for the TreeList, so the suggested approach in the KB article is invalid.
Triggered by: https://supportheroes.telerik.com/ticket/1667663

chore(TreeList): remove invalid link

---

_contentTemplates/scheduler/views.md
components/scheduler/views/multiday.md
components/scheduler/views/timeline.md

closes: https://github.com/telerik/blazor/issues/9892

docs(Scheduler): add hide all day parameter

---

components/notification/overview.md
knowledge-base/notification-single-app-instance.md

Related to https://github.com/telerik/blazor-ui/pull/308

kb(Notification): Add KB for single Notification instance

---

_contentTemplates/scheduler/views.md
components/scheduler/resource-grouping.md
components/scheduler/views/agenda.md
components/scheduler/views/day.md
components/scheduler/views/month.md
components/scheduler/views/multiday.md
components/scheduler/views/overview.md
components/scheduler/views/timeline.md
components/scheduler/views/week.md

Closes: https://github.com/telerik/blazor/issues/9889

Add Agenda view documentation article

---

components/dropdownlist/overview.md

The DropDownList no longer uses a `<select>` element in its rendering.

chore(dropdownlist): fix incorrect information

---

components/panelbar/data-binding/overview.md

The 'PanelBar Item Features' section incorrectly lists HasChildren as being a string, yet the examples show it as bool.

HasChildren is bool, not string

---

components/scheduler/views/agenda.md

Polish `Agenda` View documentation, due to additional recommendations from the tech writers.

docs(Scheduler): article polish

---

components/toolbar/appearance.md

Closes https://github.com/telerik/blazor/issues/10308

docs(ToolBar): add FillMode documentation

---

_config.yml
_contentTemplates/editor/general.md
components/editor/overview.md
security/faq.md
security/overview.md

Closes https://github.com/telerik/blazor/issues/9922

Security documentation

---

knowledge-base/common-struct-error.md

Closes: https://github.com/telerik/blazor/issues/9643

docs(common): Add KB for null exception

---

components/chart/templates.md
components/stockchart/templates.md

Closes: https://github.com/telerik/blazor/issues/10254

Add documentation articles for Chart and StockChart No Data Template

---

components/tabstrip/overview.md
components/tabstrip/tabs-alignment.md
components/tabstrip/tabs-position.md

Closes: https://github.com/telerik/blazor/issues/10390

Add tab alignment documentation

---

knowledge-base/grid-autofit-columns.md

chore(grid): clarify the required DotNetObjectReference type

---

components/combobox/overview.md

Based on customer's docs feedback.

docs(ComboBox): Improve AllowCustom description in Overview

---

components/grid/grouping/load-on-demand.md
components/grid/manual-operations.md
knowledge-base/grid-custom-grouping-order.md
upgrade/breaking-changes/7-0-0.md

The need for the update comes from the fix of [this bug](https://github.com/telerik/blazor/pull/10265).

chore(Grid): update onread examples due to a latest changes

---

components/badge/overview.md

The Badge in this example currently looks like this in the integrated REPL:

chore(Badge): fix cutout badge

---

.github/workflows/build_docs_no_api.yml
.github/workflows/publish-kb.yml
.github/workflows/pull_request.yml
.github/workflows/pull_request_closed.yml
.github/workflows/pull_request_production_closed.yml
.github/workflows/sync-a11y.yml

Related to https://github.com/telerik/blazor/issues/10607

chore: change ubuntu-latest label to ubuntu-22.04

---

components/scheduler/overview.md

closes: https://github.com/telerik/blazor/issues/10671

docs(Scheduler): add refresh method documentation

---

getting-started/vs-integration/new-project-wizard.md

Related to: https://github.com/telerik/blazor/issues/9904

docs(common): remove deprecated templates from docs

---

_contentTemplates/grid/common-link.md
components/grid/columns/command.md
components/grid/hierarchy.md
components/grid/templates/column-footer.md
components/grid/templates/column-group-footer.md
components/grid/templates/column.md
components/grid/templates/row.md
knowledge-base/grid-using-components-in-templates.md
upgrade/breaking-changes/7-0-0.md

Closes https://github.com/telerik/blazor/issues/10707

chore(Grid): document templates breaking changes

---

common-features/adaptive-rendering.md
components/rootcomponent/overview.md

Closes https://github.com/telerik/blazor/issues/10640

Document adaptive breakpoints customization

---

components/toolbar/overview.md

Closes: https://github.com/telerik/blazor/issues/10648

docs(Toolbar): add new adaptive parameter

---

components/grid/toolbar.md
components/treelist/toolbar.md

Closes: https://github.com/telerik/blazor/issues/10646

docs(Grid): add typed tools toolbar articles

---

_contentTemplates/common/get-started.md
getting-started/web-app.md
knowledge-base/common-telerik-themes-libman.md
styling-and-themes/overview.md

Part of https://github.com/telerik/blazor/issues/10824

chore(common): apply seo recommendations

---

_contentTemplates/common/inputs.md

See https://www.telerik.com/blazor-ui/documentation/components/grid/templates/editor#notes

docs(common): Remove empty line in list item that uses a template

---

components/floatingactionbutton/accessibility/wai-aria-support.md
components/toolbar/overview.md
knowledge-base/textbox-validate-on-change.md
src-a11y/configs/floatingactionbutton.aria.yml

Comes from this item, as at the time of implementation, the documentation was already merged: https://github.com/telerik/blazor/issues/10876.
Additionally, fixed the version in one KB coming from a ticket and generated the a11y article for the FAB component.

chore(Toolbar): add scroll buttons

---

components/animationcontainer/overview.md
docs-builder.yml

chore(AnimationContainer): fix animation container position

---

knowledge-base/contextmenu-disable-focus.md

chore(ContextMenu): fix incorrect selector

---

_contentTemplates/common/parameters-table-styles.md
components/grid/columns/width.md
components/treelist/columns/width.md

The PR contains two versions of some of the content. Please provide your opinion on the readability and ease of understanding.

docs(Grid): Revamp Column Width article

---

knowledge-base/window-center-programmatically.md

Related to: https://github.com/telerik/blazor/issues/8956
Once we deprecate the Centered parameter of the Window, will link this KB to Window Position documentation.

docs(Window): add kb for programmatic center of the window

---

components/grid/overview.md
getting-started/server-blazor.md
introduction.md

Related to https://github.com/telerik/blazor/issues/11272

chore: comment out video object descriptors

---

troubleshooting/nuget-feed.md

docs(common): Improve NuGet troubleshooting

---

components/window/overview.md
components/window/position.md

Related to: https://github.com/telerik/blazor/issues/8956

docs(Window): remove centered parameter

---

components/grid/export/csv.md
components/grid/export/excel.md

closes: https://github.com/telerik/blazor/issues/9380

docs(Grid): add docs for export options customizations

---

components/tooltip/overview.md

Based on customer feedback from ticket

chore(Tooltip): update parameter description

---

components/grid/export/csv.md
components/grid/export/excel.md

part of: https://github.com/telerik/blazor/issues/9380

chore(Grid): fxi api ref links

---

components/radiogroup/overview.md

Related to the newly introduced `FocusItemAsync` method in https://github.com/telerik/blazor/pull/11322.

docs(RadioGroup): update focus documentation

---

components/multiselect/custom-value.md
components/multiselect/overview.md

closes: https://github.com/telerik/blazor/issues/8693

docs(MultiSelect): add docs for custom values

---

components/multiselect/templates.md

Closes https://github.com/telerik/blazor/issues/7190

chore(MultiSelect): Add documentarion for SummaryTagtemplate

---

components/window/animation.md
components/window/overview.md

closes: https://github.com/telerik/blazor/issues/11120
To test the example in the article, use the latest version of master

docs(Window): add animation docs

---

components/notification/appearance.md

Fix typos in appearance.md

---

knowledge-base/scheduler-custom-appointment-tooltips.md

Also review https://github.com/telerik/blazor-ui/pull/326

kb(Scheduler): Revamp tooltip KB

---

knowledge-base/grid-autofit-columns.md

If observeTarget is called from setTimeout, the original parameters to the call are lost and dotNetObj and gridClass are undefined on subsequent invocations.

Update observeTarget to retain parameter passing

---

_contentTemplates/common/get-started.md
_contentTemplates/common/js-interop-file.md
common-features/icons.md
deployment/troubleshooting.md
getting-started/client-blazor.md
getting-started/server-blazor.md
getting-started/vs-code-integration/document-processing-wizard.md
getting-started/vs-code-integration/new-project-wizard.md
getting-started/vs-integration/convert-project-wizard.md
getting-started/vs-integration/options.md
getting-started/vs-integration/upgrade-wizard.md
getting-started/web-app.md
getting-started/what-you-need.md
introduction.md
knowledge-base/font-icons-not-rendering.md
knowledge-base/jquery-kendo-in-blazor.md
styling-and-themes/overview.md
troubleshooting/js-errors.md
troubleshooting/nuget-feed.md
upgrade/breaking-changes/9-0-0.md
upgrade/overview.md

Related to https://github.com/telerik/blazor/issues/11469

chore: update docs to reflect new package distribution

---

components/chiplist/events.md

OnRemove event handler does not do anything. Triggered by 1687649.
Simplify example by removing optional custom model property names.

docs(ChipList): Enhance Events example

---

components/panelbar/data-binding/overview.md
components/panelbar/templates/header.md

Closes https://github.com/telerik/blazor/issues/5075

chore(PanelBar): update field bindings docs

---

knowledge-base/grid-checkbox-column-prevent-click.md

kb(Grid): prevent checkbox column click

---

components/fileselect/events.md
components/upload/events.md

docs(FileSelect): add info about Name Html encoding

---

knowledge-base/gantt-persist-treelist-width-after-refresh.md

kb(Gantt): add Gantt TreeList width persistance kb

---

components/gantt/gantt-tree/editing/incell.md
components/gantt/gantt-tree/editing/inline.md
components/gantt/gantt-tree/editing/overview.md
components/grid/editing/incell.md
components/grid/editing/inline.md
components/grid/editing/overview.md
components/treelist/editing/incell.md
components/treelist/editing/inline.md
components/treelist/editing/overview.md

Closes: https://github.com/telerik/blazor/issues/11679

docs(Grid): add docs for new row position feature

---

components/diagram/connections.md
components/diagram/events.md
components/diagram/layouts.md
components/diagram/overview.md
components/diagram/shapes.md
docs-builder.yml
introduction.md

Some more API links will be added later.

docs(Diagram): Add Diagram component documentation

---

components/chart/overview.md

Part of: https://github.com/telerik/blazor/issues/11647

chore: replace example with live example url

---

components/dockmanager/state.md

The previous statement for resetting the DockManager state was wrong. The changes are trigger by client feedback.

chore(DockManager): update state documenation

---

components/dropdownlist/overview.md

Part of: https://github.com/telerik/blazor/issues/11647

docs(DropDownList): Change basic usage to live example

---

components/aiprompt/events.md
components/aiprompt/overview.md
upgrade/breaking-changes/10-0-0.md
upgrade/breaking-changes/list.md
upgrade/rendering-changes/10-0-0.md
upgrade/rendering-changes/list.md

closes: https://github.com/telerik/blazor/issues/11955

Aiprompt docs update

---

components/inlineaiprompt/events.md
components/inlineaiprompt/overview.md
components/inlineaiprompt/streaming.md
docs-builder.yml

Closes: https://github.com/telerik/blazor/issues/11688

docs(InlineAiPrompt): add inline ai prompt documentation

---

components/fileselect/events.md

docs: update fileselect events article

---

components/chat/data-binding.md
components/chat/events.md
components/chat/file-uploads-and-media.md
components/chat/integrations.md
components/chat/messages.md
components/chat/overview.md
components/chat/quick-actions.md
components/chat/templates.md

docs(Chat): improve examples to follow style guide
