- getting-started/client-blazor.md
- getting-started/server-blazor.md
- installation/what-you-need.md
- themes.md
This `id` was for demo purposes only.
> Removed `id` from css

- installation/nuget.md
Just a minor fix for confusing wording in the article.
> Wording change

- _contentTemplates/common/get-started.md
Fixed two small typos in the article.
> Typo fixes

- components/button/overview.md
- components/calendar/navigation.md
- components/chart/overview.md
- components/chart/types/bar.md
- components/chart/types/column.md
- components/chart/types/donut.md
- components/chart/types/pie.md
Fixed a couple of issues while reading through the documentation.
> Some minor typo fixes

- themes/custom-theme.md
- themes/overview.md
telerik/kendo-themes/issues/1218
> docs: enrich docs with additional topics on sass theme customization

- knowledge-base/chart-style-the-chart-series-labels.md
- knowledge-base/chart-style-the-series-labels.md
Created kb article illustrating how to use standard CSS within the ChartSeriesLabelsBase API to style the labels,
> kb(chart): style series labels

- knowledge-base/combobox-case-insensitive-matching.md
Made out of ticket **1460581**
> Match case insensitive user input with ComboBox

- components/checkbox/indeterminate-state.md
Related to: telerik/blazor#1102
> Further explanations to Indeterminate state in CheckBox

- components/menu/data-binding/overview.md
- components/treeview/data-binding/overview.md
Updates made in menu and treeview
> Update image precedence docs

- components/multiselect/overview.md
* OnClick
* OnChange
* ValueChanged
* OnRead
* etc.
> Docs autoclose multiselect

- knowledge-base/daterangepicker-reposition-labels.md
> KB: Reposition the Labels of the DateRangePicker

- troubleshooting/general-issues.md
> Add link to Microsoft WASM best performance practices

- components/document-processing/words.md
Please, don't push to live before the release.
> Added a bullet for content controls in WordsProcessing

- accessibility/keyboard-navigation.md
Added links to the keyboard navigation demos of Treelist and Scheduler. Link to Upload is already added.
> Docs - keyboard-navigation

- components/grid/virtual-scrolling.md
* OnClick
* OnChange
* ValueChanged
* OnRead
* etc.
> Fixed typo - mantual => manual

- integrations/unit-testing-with-justmock.md
SEO optimizations:
- changed meta description
- added meta tags
> Update unit testing with JustMock

- components/grid/selection/multiple.md
- components/grid/selection/overview.md
- components/grid/selection/single.md
- components/treelist/selection/multiple.md
- components/treelist/selection/overview.md
- components/treelist/selection/single.md
> docs(grid): checkbox only selection

- components/window/draggable.md
- components/window/events.md
> docs(window): draggable window

- components/combobox/events.md
- components/dropdownlist/templates.md
- Changed template section position in DropDownList to match others arrangement
- Fixed typo in ComboBox events section
> chore(dropdownlist,combobox):fix typo and small docs changes

- components/document-processing/pdf.md
* OnClick
* OnChange
* ValueChanged
* OnRead
* etc.
> Updated new feature for DPL (R2)

- components/grid/columns/bound.md
- components/grid/overview.md
Base for Ticket 1519283
Review and expand details as needed, maybe template this and also copy for the treelist.
> docs(grid): base classes, inheritance, only one class allowed

- knowledge-base/grid-column-in-custom-component-is-last.md
- Added tip for conditional columns in a Grid
- Added additional description for later added columns in a Grid
> chore(kb, grid):kb extentions for grid columns rendering

- installation/nuget.md
Perhaps we might get a better video that also shows the VS steps, but for now we can go live with the text instructions and clarifications on the video.
> docs(nuget): better VS NuGet setup instructions

- _contentTemplates/common/form-validation.md
- components/form/validation.md
- components/validation/overview.md
- Added important note in the Validation
Related to https://supportheroes.telerik.com/ticket/1520308 (Intern Note)
> chore(form):added important note for validation

- components/autocomplete/virtualization.md
- components/combobox/virtualization.md
- components/dropdownlist/virtualization.md
- components/multiselect/virtualization.md
> chore(dropdowns): add missing using

- knowledge-base/grid-edit-on-row-double-click.md
> Edit a Grid row on click with custom popup form

- components/numerictextbox/overview.md
From ticket, 1523266, the default value of the Decimals property was not immediately clear. 
For clarity, added where the default value comes form if it is not set.
> update decimals default value

- knowledge-base/treeview-drag-to-empty.md
Prompted by https://www.telerik.com/forums/seems-it-is-not-possible-to-drop-item-to-empty-treevew-is-t-it
> kb(treeview): drop to empty treeview

- _contentTemplates/common/general-info.md
- _contentTemplates/common/get-started.md
- _contentTemplates/common/js-interop-file.md
- getting-started/client-blazor.md
- getting-started/server-blazor.md
- getting-started/what-you-need.md
- introduction.md
This PR includes improvement suggestions for the following articles in the Getting Started section:
- Client-Side Blazor - Tutorial
- Sever-Side Blazor - Tutorial
- What You Need
The added comments try to explain the motivation behind the suggested changes.
> Edit getting started docs

- _contentTemplates/common/general-info.md
- getting-started/value-vs-data-binding.md
- getting-started/vs-code-integration/convert-project-wizard.md
- getting-started/vs-code-integration/introduction.md
- getting-started/vs-code-integration/new-project-wizard.md
- getting-started/vs-code-integration/troubleshooting.md
- getting-started/vs-integration/convert-project-wizard.md
- getting-started/vs-integration/introduction.md
- getting-started/vs-integration/latest-version-retrieval.md
- getting-started/vs-integration/new-project-wizard.md
- getting-started/vs-integration/troubleshooting.md
This PR includes continues the Getting Started section review that started with PR #375.
Included documents:
* getting-started/vs-integration
* getting-started/vs-code-integration
* getting-started/value-vs-data-binding
I inserted comments that explain the suggested changes.
> Edit getting-started/vs-integration docs

- getting-started/value-vs-data-binding.md
please merge and publish if ok
> chore(common): link valueexpression required kb from valuebinding

- accessibility/compliance.md
* OnClick
* OnChange
* ValueChanged
* OnRead
* etc.
> chore: test commit

- .github/workflows/pull_request_closed.yml
- accessibility/overview.md
* OnClick
* OnChange
* ValueChanged
* OnRead
* etc.
> Test branch 4

- knowledge-base/inputs-clear-selection-value.md
> kb(inputs): clear selection (value)

- themes/overview.md
Expands a little on https://www.telerik.com/forums/should-i-use-the-kendo-css-insted-of-bootstrap
> docs(themes): diff with bootstrap

- components/splitter/overview.md
For https://github.com/telerik/blazor-ui/pull/113
> chore(splitteR): link 100% size sample project

- _contentTemplates/common/get-started.md
instead of orange, which looks dangerous
> chore(nuget): make the tip about the new nuget source green

- knowledge-base/slider-max-parameter-zero-error.md
- Added KB for Slider with 0 Max parameter
> kb(slider):add kb for max parameter zero in slider

- components/gantt/gantt-tree/data-binding/hierarchical-data.md
- components/gantt/overview.md
This pull request fixes:
1. Broken code snippet in the Overview article
2. Replaces the Gantt Hierarchy example to not be with TreeList, but with a Gantt
> Fixes in the Gantt Docs

- styling-and-themes/custom-theme.md
It may seem very basic knowledge, but we had a ticket about this today.
> docs: Improve custom theme usage docs

- knowledge-base/form-dirty-fields.md
It was indeed easy to create KB from the admin :)  
SupportHeroes: https://supportheroes.telerik.com/ticket/1536031
Telerik Blazor Docs Card: https://github.com/telerik/blazor/projects/2#card-69265188
> chore(kb): form dirty fields kb resource

- knowledge-base/common-themebuilder-json-from-scss.md
> Update the JSON file with new syntax

- components/textbox/overview.md
Based on customer feedback - apparently some customers find it hard to achieve.
> chore(textbox): Add example for programmatically changing the value

- components/document-processing/spreadsheet.md
Please, do not upload to live prior to releasing R1 2022
> Added new feature for SpreadProcessing

- components/upload/events.md
- components/upload/overview.md
- Added the new upload methods in upload-overview
- Added an example that uses the methods 
- Added link for methods in the upload-events page
> docs(upload):added upload api methods

- components/grid/manual-operations.md
> chore(grid): move @functions code block to @code

- components/grid/editing/validation.md
- components/grid/templates/filter.md
- Small typo fixes in Grid Filter Menu Template and Validation
> chore(grid):small typo fixes

- components/grid/filter/filter-row.md
https://demos.telerik.com/blazor-ui-dev/grid/filter-row
> chore(grid): update filter row documentation about disabled clear filter

- knowledge-base/inputs-floating-label.md
https://github.com/telerik/blazor/issues/2436
Any changes are welcome. I have added link to the release notes, so ping me if we need an update there.
> chore(kb): add kb for floating label

- components/daterangepicker/overview.md
-Fixed link to the live demo in the "See Also" section
> docs(daterangepicker): fixed demo link

- _contentTemplates/grid/state.md
- _contentTemplates/treelist/state.md
- components/grid/state.md
- components/treelist/state.md
-Changed FilterDescriptorBase to IFilterDescriptor in Grid and TreeList examples
> docs(grid-treelist): fixed FilterDescriptorBase

- _contentTemplates/common/get-started.md
- _contentTemplates/grid/state.md
- common-features/input-validation.md
- components/checkbox/events.md
- components/checkbox/indeterminate-state.md
- components/chunkprogressbar/indeterminate.md
- components/dialog/action-buttons.md
- components/dialog/events.md
- components/dialog/header.md
- components/dialog/overview.md
- components/drawer/templates.md
- components/form/formitems/buttons.md
- components/grid/filter/searchbox.md
- components/loader/overview.md
- components/panelbar/templates/content.md
- components/progressbar/indeterminate.md
- components/progressbar/overview.md
- components/treelist/filter/searchbox.md
- components/wizard/structure/buttons.md
- knowledge-base/common-css-isolation.md
- knowledge-base/common-validation-error-in-tooltip.md
- knowledge-base/form-chrome-autofill.md
- knowledge-base/form-justify-formbuttons.md
- knowledge-base/grid-edit-on-row-double-click.md
- knowledge-base/tooltip-no-update-from-main-model.md
- knowledge-base/window-in-form-edit-context.md
- knowledge-base/window-open-from-another-component.md
- styling-and-themes/form-elements.md
-Changed button's Primary parameter to ThemeColor on documentation and knowledge base articles.
> fix(docs-kb): primary button

- components/menu/overview.md
This PR updates the Menu component Overview page according to the guidelines [in this document](https://progresssoftware-my.sharepoint.com/:w:/g/personal/ymitev_progress_com/EXwTNq51uIxIrstak1fv1BABO6BN08SR3A4zhoubKvknyg?e=Sjz3uT).
The Menu is one of the ten initial components that will undergo this transformation.
> Update Menu Overview

- _contentTemplates/grid/state.md
-Changed ExpandedItems to a collection due to braking change
-Changed the Primary parameter of the button to ThemeColor
> docs(grid): fixed hierachy grid example

- components/grid/state.md
`ColumnStates` now includes more fields. Listed them all and tweaked the snippet.
> Grid docs: Update ColumnStates section

- components/numerictextbox/overview.md
-Added the placeholder in features sections in the overview page of the documentation.
> [3.1] Added placeholder feature

- components/textbox/overview.md
- Removed Label from examples and features list
- Added KB article that shows how to add floating label
> docs(textbox): removed Label

- knowledge-base/buttongroup-vertical.md
> docs: Add KB for vertical ButtonGroup

- components/listview/editing.md
- components/listview/events.md
- components/listview/templates.md
- components/maskedtextbox/events.md
- components/maskedtextbox/mask-prompt.md
- components/maskedtextbox/overview.md
- knowledge-base/common-time-duration-input.md
- knowledge-base/form-chrome-autofill.md
- knowledge-base/inputs-align-text-right.md
- knowledge-base/numerictextbox-percentage-range.md
- knowledge-base/textbox-add-icon.md
- knowledge-base/textbox-chrome-autofill-label.md
- styling-and-themes/form-elements.md
https://teams.microsoft.com/l/message/19:12463c0e02e44f3385a09b71af5f9832@thread.skype/1645653357450?tenantId=db266a67-cbe0-4d26-ae1a-d0581fe03535&groupId=bd850467-c897-42fb-9c6d-f008ef217edc&parentMessageId=1645653357450&teamName=Blazor%20Team&channelName=Docs-Demos&createdTime=1645653357450
> Remove Label parameter

- components/grid/editing/overview.md
- components/grid/events.md
- components/treelist/editing/overview.md
- components/treelist/events.md
- Added the event in the Grid and TreeList events article.
> [3.1] docs(grid): Add OnAdd event documentation

- _config.yml
- components/floatinglabel/overview.md
- components/floatinglabel/validation.md
- knowledge-base/inputs-floating-label.md
- upgrade/breaking-changes/3-0-0.md
Related to https://github.com/telerik/blazor/issues/3103
> [3.1] docs: Add FloatingLabel documentation

- _contentTemplates/grid/state.md
Related to https://github.com/telerik/blazor/issues/3937
> Note: I checked the checkbox for creating a pull request to production, but not getting one (maybe requires the pr to master to be merged). Either way, let me know if this is incorrect according to the deadline for the documentation [release candidate](https://github.com/telerik/blazor/milestone/59)
> [3.1] chore(grid): update docs for filters in state

- components/filter/integration.md
-Removed hard-coded URL from caption
> docs(filter): fix hardcoded link

- components/filter/overview.md
- knowledge-base/multiselect-checkbox-in-dropdown.md
- Needed fix on the checkbox CSS Class because of the latest version changes
- I also fixed one typo in the filter
> kb(multiselect): updated multiselect checkbox kb to the latest version

- _contentTemplates/date-inputs/format-placeholders.md
- components/datepicker/overview.md
This PR updates the DatePicker component Overview page according to the guidelines [in this document](https://progresssoftware-my.sharepoint.com/:w:/g/personal/ymitev_progress_com/EXwTNq51uIxIrstak1fv1BABO6BN08SR3A4zhoubKvknyg?e=Sjz3uT).
The DatePicker is one of the ten initial components that will undergo this transformation.
> Update DatePicker Overview

- knowledge-base/multiselect-checkbox-in-dropdown.md
Inspired by Ticket ID: 1529738
Please merge and upload live.
> kb(multiselect): select all checkbox

- _contentTemplates/dropdowns/features.md
- _contentTemplates/slider/common.md
- components/autocomplete/overview.md
- components/card/overview.md
- components/combobox/overview.md
- components/combobox/pre-select-item.md
- components/dropdownlist/overview.md
- components/dropdownlist/pre-select-item.md
- components/multiselect/overview.md
- components/multiselect/pre-select-items.md
- components/rangeslider/decimals.md
- components/rangeslider/overview.md
- components/rangeslider/steps.md
- components/slider/decimals.md
- components/slider/overview.md
- components/slider/steps.md
Updated components:
- Autocomplete
- ComboBox
- DropDownList
- Multiselect
- RangeSlider
- Slider
- Card
> [3.1]Revamp overview dropdowns, sliders

- _contentTemplates/common/get-model-from-dropdowns.md
* OnClick
* OnChange
* ValueChanged
* OnRead
* etc.
> spelling fix

- components/grid/filter/searchbox.md
- components/treelist/filter/searchbox.md
Related to https://github.com/telerik/blazor/issues/4161
> [3.2] docs(grid,treelist): documentation for SearchBox enhancements

- components/datepicker/overview.md
Consider doing the same for the other pickers
> chore(datePicker): clarify Enabled

- components/toolbar/built-in-tools.md
- components/toolbar/overview.md
- components/toolbar/separators.md
- 3 new parameters were documented (Adaptive, Overflow, OverflowText)
- Added one example for the responsive overflow popup
> [3.2] docs(toolbar): Responsive Overflow Popup

- components/toolbar/built-in-tools.md
- components/toolbar/overview.md
- components/toolbar/separators.md
- Technical fixes as per comments.
> [3.2] docs(toolbar): Responsive Overflow Popup fixes

- components/treelist/events.md
> fix(treelist): expand collapse event example is not working

- components/combobox/events.md
- components/dropdownlist/events.md
- components/multiselect/events.md
> docs(dropdownlist): Improve ValueChanged lambda expression information

- _config.yml
- getting-started/repl/intergration.md
- getting-started/repl/overview.md
- getting-started/repl/snippets-and-scaffolders.md
Related to https://github.com/telerik/blazor/issues/4270
> docs(repl):snippets and scaffolders in repl

- components/grid/editing/popup.md
- components/treelist/editing/popup.md
- knowledge-base/grid-popup-edit-title.md
> docs(grid): Add KB for dynamic popup edit form title

- knowledge-base/grid-dynamic-columns-with-static.md
Based on https://www.telerik.com/forums/should-key-be-used-explicitly-with-telerik-blazor
> docs(grid): Update @key values in dynamic columns KB

- _contentTemplates/common/general-info.md
- getting-started/vs-code-integration/scaffolders.md
- getting-started/vs-integration/new-project-wizard.md
- getting-started/vs-integration/scaffolders.md
- Added a new section for the Visual Studio Scaffolders in the Getting Started tab keeping it consistent with the Visual Studio Code Scaffolders section.
> docs(vs-integration): Visual Studio Scaffolders

- components/grid/templates/filter.md
CheckedItems is not updated when the user clicks on the Clear button.
> docs(grid): Fix bug in custom checkbox filtering example

- styling-and-themes/swatch-distribution.md
- upgrade/overview.md
* Added manual theme replacement to the Update Process.
* Removed some off topic content in the Swatch documentation, which distracts from the important note afterwards.
> docs(common): Improve Upgrade Process

- hybrid-blazor-apps.md
> docs(common): Added note about iOS AOT and JIT compilation issues

- _contentTemplates/common/observable-data.md
- _contentTemplates/common/rebind-method.md
- components/carousel/refresh-data.md
- components/gantt/events.md
- components/gantt/refresh-data.md
- components/grid/refresh-data.md
- components/panelbar/events.md
- components/panelbar/refresh-data.md
- components/treelist/refresh-data.md
- components/treeview/refresh-data.md
Apart from the Gantt, there are a couple other components that [expose Rebind](https://github.com/telerik/blazor/issues/4291), however, their Refresh data articles were not updated.
The PR includes Rebind documentation for:
> [3.6] docs(gantt,treelist): Documentation for Rebind method

- components/document-processing/spreadstream.md
> Added import for SpreadStreamProcessing

- components/notification/overview.md
> chore(notification): fix anchor link

- components/grid/templates/editor.md
> docs(grid): Revamp Editor Template article

- components/radiogroup/events.md
- components/radiogroup/label-position.md
- components/radiogroup/layout.md
- components/radiogroup/overview.md
- components/radiogroup/templates.md
Related to https://github.com/telerik/blazor/issues/5575
> docs(radiogroup): Document ItemTemplate

- components/chart/plot-bands.md
> docs(chart): Revamp Chart PlotBands article

- components/tilelayout/state.md
> docs(tilelayout): Expose KB in State article

- components/chart/data-bind.md
- knowledge-base/chart-newtonsoft-seialization-settings.md
> docs(chart): Improve data binding documentation

- _contentTemplates/upload/notes.md
- components/upload/events.md
- components/upload/overview.md
- components/upload/troubleshooting.md
The main purpose was to make the content about sending custom data more visible and better structured.
The initiative transformed into a total revamp, refactoring, optimization and adding of new information.
> docs(upload): Revamp Events

- knowledge-base/editor-add-text-templates.md
Pr with clean history - ref: https://github.com/telerik/blazor-docs/pull/1250
> kb(editor):add templates

- knowledge-base/animationcontainer-close-on-outside-click.md
- knowledge-base/blazor-in-asp-net.md
- knowledge-base/button-change-icons-position.md
- knowledge-base/buttongroup-mixed-selection-mode.md
- knowledge-base/grid-import-excel.md
Related to : [telerik/blazor#4905](https://github.com/telerik/blazor/issues/4905)
> Added kb about how to import excel file data in a Grid

- troubleshooting/nuget-feed.md
This is part of a general WCT initiative to advertise our status page. I used the opportunity to improve the article structure and add more information.
> docs(common): Revamp NuGet troubleshooting article

- hybrid-blazor-apps.md
please merge the PR as I will not be able to track it
> refactor: fix link to live demos

- getting-started/repl/intergration.md
- getting-started/repl/overview.md
- getting-started/repl/snippets-and-scaffolders.md
- getting-started/repl/user-snippets.md
Related to [this discussion](https://github.com/telerik/blazor-docs/pull/1379#discussion_r1155618714) - fixing misunderstanding
> docs(repl):update user snippets docs

- components/grid/state.md
> docs(Grid): Fix broken edit-via-state example

- components/button/icons.md
> docs(button): Improve Icons documentation

- styling-and-themes/override-theme-styles.md
> docs(common): Improve CSS Overrides article

- components/notification/open-close-hide.md
- components/notification/overview.md
Related to: [telerik/blazor#6542](https://github.com/telerik/blazor/issues/6542)
> Enhanced Overview and Open-Close-Hide articles

- .github/workflows/sync-a11y.yml
> chore: update sync-a11y yml to support akeyless

- components/window/overview.md
Related to: https://github.com/telerik/blazor/issues/6304.
> [4.3] docs(window): Revamp Overview docs page

- getting-started/hybrid-blazor.md
- getting-started/what-you-need.md
- hybrid-blazor-apps.md
Related to: https://github.com/telerik/blazor/issues/5097.
> [4.3] docs(common):add hybrid template getting started documentation

- components/dialog/overview.md
Related to: [telerik/blazor#6527](https://github.com/telerik/blazor/issues/6527)
> docs(dialog): enhance refresh method description

- knowledge-base/grid-hide-header-row.md
Related to: [telerik/blazor#6641](https://github.com/telerik/blazor/issues/6641)
> docs(kb): hide the grid header row

- system-requirements.md
> chore: state correct version for last supported .net3.1

- .github/workflows/build_docs_no_api.yml
- .github/workflows/ci.yml
> chore: add ci workflow

- knowledge-base/radiogroup-bind-to-enum.md
Manual cherry pick of https://github.com/telerik/blazor-docs/pull/1501
> Production - chore: add kb for binding radiogroup to enum

- components/dropdownlist/overview.md
Update information in "Creating the DropDownList" section
> Update overview article

- components/chart/types/radar-column.md
Remove `ColorField` property - it is not yet supported for this Chart type.
> Update Radar Column Chart overview

- styling-and-themes/themebuilder.md
I'm adding the suggested improvements for this article on behalf of the Fiddler team, who are currently providing assistance to the ThemeBuilder.
> chore(themebuilder): update themebuilder overview article

- _config.yml
- components/chart/pan-and-zoom/pan.md
- components/chart/pan-and-zoom/zoom.md
- components/chart/pan-zoom.md
Related to: https://github.com/telerik/blazor/issues/6877.
> [4.4] docs(charts): add pan and zoom docs

- components/pivotgrid/overview.md
Related to: https://github.com/telerik/blazor/issues/6905.
> [4.4] docs(pivotgrid): add headerclass parameter

- components/pivotgrid/overview.md
Related to: https://github.com/telerik/blazor/issues/6899.
> [4.4] docs(pivotgrid): add row and column header width parameters

- components/grid/columns/menu.md
Review of https://github.com/telerik/blazor-docs/pull/1546.
As the GIF is missing, I removed the line that inserts it.
> Review Column Menu - Groupable and Reorderable

- knowledge-base/listview-popup-editing.md
Related to https://feedback.telerik.com/blazor/1617531
> docs(listview): Add popup editing KB

- globalization/localization.md
> docs(localization): Remove obsolete info and refactor code

- components/window/overview.md
- knowledge-base/window-does-not-display-child-items-data.md
Related to: https://github.com/telerik/blazor/issues/6304.
> docs(window): Add no data displayed KB

- components/grid/paging.md
https://feedback.telerik.com/blazor/1620328-blazor-documentation-bug
> docs(grid): fix broken example in the Paging article

- components/chart/labels-template-and-format.md
- knowledge-base/chart-format-percent.md
- knowledge-base/chart-localized-labels.md
- troubleshooting/csp.md
Related to https://github.com/telerik/blazor/issues/7250#issuecomment-1690418430
> docs(common, chart): Update CSP information and Chart label template examples

- components/gantt/gantt-tree/data-binding/overview.md
- components/gantt/gantt-tree/editing/popup.md
- components/gantt/gantt-tree/templates/popup-form-template.md
Related to: https://github.com/telerik/blazor/issues/6392
> Documentation for Redesign Gantt Popup Editing Form

- components/splitbutton/icons.md
> Fix spelling error

- knowledge-base/grid-filter-edit-enum.md
Add `[Display(Name = "...")]` based on a customer feedback.
> Update KB: Filter and Edit Enum in Grid

- components/treeview/selection/single.md
> Fix typo in single.md

- components/filemanager/context-menu.md
- components/filemanager/data-binding/flat-data.md
- components/filemanager/data-binding/hierarchical-data.md
- components/filemanager/data-binding/overview.md
- components/filemanager/events.md
- components/filemanager/overview.md
- components/filemanager/preview-pane.md
- components/filemanager/search.md
- components/filemanager/selection.md
- components/filemanager/sort.md
- components/filemanager/upload.md
- components/filemanager/views.md
- Fix paths for proper Breadcrumb behavior
- Ensure `New Folder` button works as expected (handle `OnModelInit` where missing)
- Update code to follow the style guide
> docs(filemanager): Update samples

- components/splitter/panes.md
Related to: https://github.com/telerik/blazor/issues/7387
> docs(splitter): add visible parameter information

- getting-started/client-blazor.md
- getting-started/server-blazor.md
Addressing docs feedback for https://docs.telerik.com/blazor-ui/getting-started/server-blazor
> Says we need to select our theme, but doesn't provide us with the list of possible values. Am I expected to guess URLs?
> docs(common): Improve theming getting started experience

- components/avatar/types.md
Based on an anonymous feedback.
> docs(avatar): fix types article sample

- _contentTemplates/date-inputs/general.md
Related to: https://github.com/telerik/blazor/issues/7562
> docs(dateinput): add formatplaceholder day period parameter

- components/tilelayout/overview.md
- components/tilelayout/resize.md
Related to https://github.com/telerik/blazor/issues/7424
> chore(tilelayout): clarify resizing prerequisite

- components/tabstrip/persist-content.md
> docs(tabstrip): clarify persisttabcontent behavior

- components/dropzone/overview.md
Related to: [#7712](https://github.com/telerik/blazor/issues/7712)
> docs(dropzone): multiple property documentation

- knowledge-base/common-readonly-properties
Related to: [#7373](https://github.com/telerik/blazor/issues/7373)
> docs(common): add kb for read-only properties

- components/menu/events.md
> [5.1]docs(menu): documentation for menu item render event

- _contentTemplates/dropdowns/features.md
Coming from: 1632035. Our documentation needs to clarify this behavior.
> docs(dropdown): enhance popup settings section

- components/treeview/data-binding/hierarchical-data.md
> docs(treeview): Add more levels to Hierarchy Data Binding article

- knowledge-base/listview-popup-editing.md
> docs(listview): fix kb example bug

- components/contextmenu/events.md
Related to: [#8166](https://github.com/telerik/blazor/issues/8166)
> [5.1]docs(contextmenu): item render event documentation

- components/dropdownlist/overview.md
- components/editor/custom-tools.md
- components/editor/overview.md
- components/form/formitems/buttons.md
- components/form/overview.md
- components/pdfviewer/events.md
- components/pdfviewer/overview.md
- components/pdfviewer/toolbar.md
Related to https://github.com/telerik/blazor/issues/8069
> SEO housekeeping

- components/filemanager/context-menu.md
- components/filemanager/data-binding/flat-data.md
- components/filemanager/data-binding/hierarchical-data.md
- components/filemanager/data-binding/overview.md
- components/filemanager/events.md
- components/filemanager/overview.md
- components/filemanager/preview-pane.md
- components/filemanager/search.md
- components/filemanager/selection.md
- components/filemanager/sort.md
- components/filemanager/upload.md
- components/filemanager/views.md
This enhancement is a result of this discussion: https://github.com/telerik/blazor/issues/7111#issuecomment-1877087480
> docs(filemanager): fix docs samples

- components/treelist/accessibility/overview.md
- components/treelist/accessibility/wai-aria-support.md
- src-a11y/configs/treelist.aria.yml
Related to: https://github.com/telerik/blazor/issues/7624.
> [5.1] docs(a11y): add treelist example that cover latest wcag guidelines

- components/chip/events.md
- components/chip/overview.md
Also added the `Selected` parameter to the table as it was missing.
> [5.1] docs(chip): Document Selectable parameter

- components/chip/appearance.md
There is no `ThemeConstants.Chip.FillMode.None`.
> chore (chip): update FillMode values table

- .github/workflows/build_docs_no_api.yml
> update container to latest

- components/grid/editing/overview.md
- knowledge-base/grid-add-edit-state.md
> chore(grid): link programmatically entering edit mode from editing overview

- components/button/appearance.md
- components/buttongroup/appearance.md
- components/togglebutton/appearance.md
Related to https://github.com/telerik/blazor/issues/8795
> chore(button, buttongroup, togglebutton): add clear fill mode in appearance article

- accessibility/keyboard-navigation.md
- accessibility/wcag-section-508-wai-aria.md
Related to: https://github.com/telerik/blazor/issues/8826
> docs(ListView): keyboard navigation documentation

- knowledge-base/common-css-isolation.md
Related to: https://github.com/telerik/blazor/issues/8230
> kb(cssIsolation): make snippets non-runnable

- components/filter/overview.md
https://github.com/telerik/blazor/issues/8902
> docs(filter): Add Filter Rebind() method

- components/grid/grouping/aggregates.md
Related to https://github.com/telerik/blazor/issues/8848
> docs(grid) Documented expose aggregates for all fields

- _contentTemplates/common/get-started.md
- getting-started/client-blazor.md
- getting-started/hybrid-blazor.md
- getting-started/server-blazor.md
- getting-started/web-app.md
- getting-started/what-you-need.md
- introduction.md
This is a consequence of the changes in https://github.com/telerik/blazor-docs/pull/1974 and a discussion with @ikoevska
> docs(common): Rename and reorder the Workflow article

- knowledge-base/fileselect-disable-onselect.md
Related to: https://github.com/telerik/blazor/issues/8680
> kb(FileSelect): disable fileselect and change caption

- components/window/position.md
A few important updates to https://github.com/telerik/blazor-docs/pull/1995/files
> docs(window): update initial ContainmentSelector documentation

- components/tooltip/overview.md
Related to: https://github.com/telerik/blazor/issues/8670
> docs(Tooltip): add hide and show delay parameters

- _config.yml
- components/rating/events.md
- components/rating/label.md
- components/rating/overview.md
- components/rating/precision.md
- components/rating/selection.md
- components/rating/templates.md
Related to: https://github.com/telerik/blazor/issues/8125
> Rating documentation

- knowledge-base/scheduler-display-allday.md
Related to: https://github.com/telerik/blazor/issues/4925
> kb(Scheduler): display in scheduler allday events

- components/grid/grouping/load-on-demand.md
> docs(grid): Show how to toggle LoadGroupsOnDemand

- components/multiselect/filter.md
- components/multiselect/overview.md
Related to https://github.com/telerik/blazor/issues/8905.
> docs(MultiSelect): document PersistFilterOnSelect feature

- _assetsApi/docfx-tmpl/src/partials/footer.tmpl.partial
- _config.yml
Integrated new feedback form and replaced sheetId with productCode
> Integrate new feedback form

- components/scheduler/views/day.md
- components/scheduler/views/month.md
- components/scheduler/views/multiday.md
- components/scheduler/views/timeline.md
- components/scheduler/views/week.md
Related to: https://github.com/telerik/blazor/issues/8686
> docs(Scheduler)documentation for ItemsPerSlot parameter

- components/dialog/integration.md
- components/dialog/overview.md
Related to https://github.com/telerik/blazor/issues/8980
> docs(dialog)integration with other components

- README.md
- package.json
> docs(common): Align license information

- components/chart/types/donut.md
> docs(chart): Remove label template from example

- components/grid/state.md
> docs(grid): Improve notes in the State Methods section

- components/multiselect/overview.md
`MinLength` can be 0. In fact, this is the default value.
> Update MinLength description

- knowledge-base/contextmenu-disable-focus.md
Related to: [8241](https://github.com/telerik/blazor/issues/8241)
> kb(ContextMenu): add kb for disable focus on first item

- knowledge-base/drawer-chart-refresh.md
Github Item: https://github.com/telerik/blazor/issues/5281
> kb(drawer): refresh a chart inside a drawer

- knowledge-base/tooltip-callout-position.md
Related to: [#7749](https://github.com/telerik/blazor/issues/7749)
> kb(Tooltip): kb for changing callout position

- knowledge-base/grid-autofit-columns.md
Related to: https://github.com/telerik/blazor/issues/9117
> docs(grid):update autofit grid kb

- knowledge-base/grid-allow-prevent-row-selection.md
Related to: [9171](https://github.com/telerik/blazor/issues/9171)
> kb(Grid): add kb for allow/prevent a row selection

- knowledge-base/grid-line-breaks.md
> kb(Grid): line breaks in grid column

- components/grid/virtual-scrolling.md
Related to: https://github.com/telerik/blazor/issues/9209
> [Grid] Revamp the Virtual Scrolling article

- components/chart/overview.md
- knowledge-base/chart-print-chart-only.md
- knowledge-base/chart-responsive.md
Cherry-pick these changes to prod https://github.com/telerik/blazor-docs/pull/2094
> docs(chart):update KB for responsive Chart (#2094)

- components/breadcrumb/overview.md
Related to https://github.com/telerik/blazor/issues/9139
> docs(Breadcrumb): add Size parameter

- components/grid/columns/reorder.md
> docs(Grid): fix typo in reoder columns

- components/splitter/accessibility/overview.md
Related to: https://github.com/telerik/blazor/issues/8564
> docs(splitter): add a11y draggable section with the sample

- knowledge-base/grid-filterrow-bool-customization.md
Related to: [#9458](https://github.com/telerik/blazor/issues/9458)
> docs(Grid): add kb for filterrow bool customization

- components/splitter/accessibility/overview.md
- components/tilelayout/accessibility/overview.md
Related to: https://github.com/telerik/blazor/issues/8564
> docs(tilelayout): add a11y draggable section with the sample

- upgrade/rendering-changes/6-0-0.md
> docs(TileLayout): rendering changes typo

- components/gantt/accessibility/overview.md
Related to: https://github.com/telerik/blazor/issues/8564
> docs(Gantt): add a11y draggable section with the sample

- components/window/accessibility/overview.md
Related to: https://github.com/telerik/blazor/issues/8564
> docs(Dialog): add a11y draggable section with the sample

- _contentTemplates/dropdowns/features.md
Related to: [#9366](https://github.com/telerik/blazor/issues/9366)
> docs(Dropdowns): update height parameter description

- upgrade/rendering-changes/6-0-0.md
Related to https://github.com/telerik/blazor/issues/9625
> docs(PdfViewer):update rendering changes

- components/calendar/overview.md
- components/calendar/selection.md
- components/daterangepicker/overview.md
Related to https://github.com/telerik/blazor/issues/8689#issuecomment-2213304274
> chore(Calendar,DateRangePicker):update reverse selection docs

- components/map/layers/shape.md
Update the code as it does not work in REPL due to the WebClient usage.
> Update broken sample

- introduction.md
Related to: https://github.com/telerik/blazor/issues/9342
> docs(common): add page templates and building blocks section

- components/dropdownlist/overview.md
- components/filemanager/views.md
- components/form/formitems/buttons.md
- components/form/overview.md
- components/grid/overview.md
- components/pdfviewer/events.md
- components/pdfviewer/overview.md
- components/pdfviewer/toolbar.md
- knowledge-base/grid-inline-edit-form.md
Related to: https://github.com/telerik/blazor/issues/9710
> docs(common): apply seo recommendations

- knowledge-base/common-navigate-from-button.md
> Update the code snippet in the Navigate from Button KB

- components/card/overview.md
- components/carousel/overview.md
- components/pager/overview.md
Related to: https://github.com/telerik/blazor/issues/9737
> Document minor enhancements

- components/grid/columns/command.md
> docs(grid): Improve CommandColumn context example

- knowledge-base/common-onchange-fires-twice.md
Related to https://github.com/telerik/blazor/issues/9418
> docs(dropdownlist): Revamp KB OnChange fires twice

- components/sankey/data-bind.md
- components/sankey/elements/labels.md
- components/sankey/elements/legend.md
- components/sankey/elements/links.md
- components/sankey/elements/nodes.md
- components/sankey/elements/title.md
- components/sankey/elements/tooltip.md
- components/sankey/events.md
- components/sankey/overview.md
Closes https://github.com/telerik/blazor/issues/9270
> chore(sankey): polish sankey docs

- components/dropdownlist/overview.md
recommended by the SEO team as the overview docs article is the one we are aiming to rank higher.
> chore(dropdownlist): remove link

- getting-started/vs-integration/new-project-wizard.md
Related to: https://github.com/telerik/blazor/issues/9898
> docs(templates): add deprecation announcement

- components/scheduler/toolbar.md
Related to: https://github.com/telerik/blazor/issues/9883
> docs(Scheduler): add toolbar article

- components/scheduler/templates/appointment.md
- components/scheduler/templates/dateheader.md
- components/scheduler/templates/resource-grouping-header.md
- components/scheduler/templates/slot.md
Related to https://github.com/telerik/blazor/issues/9886
> docs(Scheduler): Add resource grouping header template documentation

- components/treelist/selection/cells.md
Related to https://github.com/telerik/blazor/issues/9789
> docs(TreeList): add references in TreeListSelectedCellDescriptor article

- styling-and-themes/themebuilder.md
The PR extends the TB article by adding short descriptions of the key TB features.
@simonssspirit
> Add Key ThemeBuilder Features

- upgrade/overview.md
Closes: https://github.com/telerik/blazor/issues/10054
> Update the upgrade process section

- knowledge-base/grid-scroll-to-selected-row.md
Closes: https://github.com/telerik/blazor/issues/9727
> docs(Grid): Add KB for programmatically row selection and scroll to row

- common-features/input-adornments.md
- common-features/input-validation.md
- components/autocomplete/filter.md
- components/autocomplete/overview.md
- components/combobox/appearance.md
- components/combobox/filter.md
- components/combobox/overview.md
- components/combobox/pre-select-item.md
- components/multicolumncombobox/appearance.md
- components/multicolumncombobox/overview.md
- components/multiselect/overview.md
- components/multiselect/pre-select-items.md
- components/multiselect/tag-mode.md
- knowledge-base/combobox-clear-button-click.md
- knowledge-base/combobox-not-closing.md
- knowledge-base/dropdown-kb-bind-to-enum.md
- knowledge-base/dropdowns-readonly-struct-error.md
- knowledge-base/inputs-align-text-right.md
- knowledge-base/multiselect-always-select-item-limit-total.md
- styling-and-themes/override-theme-styles.md
Closes: https://github.com/telerik/blazor/issues/10541
> docs(common): replace ClearButton parameter

- installation/nuget.md
Moving this https://github.com/telerik/blazor-docs/pull/2577 to production as the automatic cherry-pick failed.
> chore(common): update package source mapping

- components/tabstrip/overview.md
- components/tabstrip/scrollable-tabs.md
- components/tabstrip/sizing.md
closes: https://github.com/telerik/blazor/issues/10650
> docs(TabStrip): add adaptive tabstrip docs

- common-features/extensions-ai-integration.md
- common-features/microsoft-extensions-ai-integration.md
- components/aiprompt/overview.md
Closes https://github.com/telerik/blazor/issues/10552
> Document integration with Microsoft.Extensions.AI

- components/grid/export/csv.md
- components/grid/export/excel.md
part of: https://github.com/telerik/blazor/issues/9380
> chore(Grid): fix api ref links

- knowledge-base/inputs-set-focus.md
Related to: https://github.com/telerik/blazor/issues/9466
> chore: update kb content

- components/grid/templates/popup-form-template.md
The example is now consistent with the ones in the Editing section.
> docs(Grid): Revamp Popup Form Template example

- components/aiprompt/overview.md
- components/aiprompt/views/commands.md
- components/editor/ai-integration/integration-with-aiprompt.md
- components/editor/ai-integration/integration-with-inline-prompt.md
- components/editor/ai-integration/overview.md
- docs-builder.yml
Closes https://github.com/telerik/blazor/issues/11163
> Editor AI integration documentation

- components/upload/chunk-upload.md
- components/upload/events.md
- components/upload/overview.md
closes: https://github.com/telerik/blazor/issues/9379
> docs(Upload): add chunk upload docs

- components/splitter/panes.md
For the next release, do not merge to production.
> docs(Splitter): Add pane Scrollable parameter

- .github/copilot-instructions.md
closes: https://github.com/telerik/blazor/issues/11747
> chore: add copilot instruction file

- components/pdfviewer/form-filling.md
- components/pdfviewer/overview.md
Part of: https://github.com/telerik/blazor/issues/11647
> docs(PdfViewer): change overview example to live

- ai/copilot-extension.md
Clarify installation instructions for Telerik Blazor Copilot extension.
> Update installation instructions for clarity
